### ISSUE TITLE
Socks5 reader parse ipv4/ipv6 in a wrong way

### ISSUE THREAD

**Issue by chhsiao90** [mike820324/socks5#1]
The problem occurred at reader when parse request with the destination address
The reader try parse the ipv4 address from request with 4-byte-length string
But actually, parse it as a string is wrong.

Same problem occured at IPV6 type.

https://github.com/mike820324/socks5/blob/master/socks5/reader.py#L61-L71

``` python
data_without_header = data[4:]
        if atyp == ADDR_TYPE["IPV4"]:
            addr, port = struct.unpack('!4sH', data_without_header)

        if atyp == ADDR_TYPE["IPV6"]:
            addr, port = struct.unpack('!16sH', data_without_header)

        if atyp == ADDR_TYPE["DOMAINNAME"]:
            _length = int(struct.unpack('B', data_without_header[0])[0])
            addr, port = struct.unpack(
                '!x{0}sH'.format(_length), data_without_header)
```

I would like to create PR for it.

**Comment by chhsiao90** [comment]
ping @mike820324
Please watch this project!! hahaha

BTW, microproxy had used [ipaddress](https://docs.python.org/3/library/ipaddress.html) (Built-in package in python3) for parsing
I'm not sure that if you concerned or not if we used ipaddress here
Because I think used it will simplify the code here but may increase the dependency when we use py2.7.

Any idea?

**Comment by mike820324** [comment]
Fixed in current master
