### ISSUE TITLE
Add unittest for project

### ISSUE THREAD

**Issue by mike820324** [mike820324/socks5#3]
Add unittest for current code.

**Comment by chhsiao90** [comment]
I would like to help on this issue!

**Comment by mike820324** [comment]
Go ahead, I'll work on server state and command line interface refactor after this issue is done.

**Comment by chhsiao90** [comment]
BTW, which notation wrap the str you prefer, single quote or double qoute?

**Comment by mike820324** [comment]
Oh I thought it was microproxy . Currently, there are still some interface that I would like to change, I thinks the unit test part should postpone when the interface is finished.
Thanks for your kindly help.

**Comment by mike820324** [comment]
As for the double quote and single quote issue, what does most project do, then we follow it.

**Comment by chhsiao90** [comment]
NP.
I was already start work on reader.
I will still push it once it was done.
If it need delete in the future, then delete it!

**Comment by mike820324** [comment]
Resolved via https://github.com/mike820324/socks5/commit/ab5827a4fb413c5c654e8a2bfe5e594adcb342f0
